### ISSUE TITLE
Embedded null character in path

### ISSUE THREAD

**Issue by desmando** [plugwash/raspbian-tools#11]
I get the following error when I try to sync my local mirror:
`Traceback (most recent call last):
  File "/home/pi/raspbmirror.py", line 737, in <module>
    if os.path.exists(filepath):
  File "/usr/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
ValueError: stat: embedded null character in path
`
I added a line to the python file to print the filepath that is being processed and it is "b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/opt/mirror/tmp/raspbian~dists~bookworm-staging~main~binary-armhf~Packages.gz.new'"
The file (without the nulls) does not exist.

**Comment by desmando** [comment]
`b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/opt/mirror/tmp/raspbian~dists~bookworm-staging~main~binary-armhf~Packages.gz.new'
`

**Comment by plugwash** [comment]
My best guess would be raspbmirrordownloads.txt (used to track downloads, so that if raspbmirror crashes the next raspbmirror run can clean up) has somehow become corrupt. Can you look at that file and tell me if you see nulls in it?

**Comment by desmando** [comment]
I've got a raspbmirrordownloads.txt.new file that has a bunch of ^@ in it. Just remove those? remove the entire line?

**Comment by plugwash** [comment]
Yeah, i'd remove the lines with nulls on them and try running rasbpmirror again.

**Comment by desmando** [comment]
That worked perfectly. Thanks.
