### ISSUE TITLE
What blocks stale PRs

### ISSUE THREAD

**Issue by Alextopher** [plugwash/raspbian-tools#13]
I'm planning on creating a Rasbian mirror soon. I was wondering what is blocking stale PRs from being merged. Integration testing perhaps?

**Comment by plugwash** [comment]
Partly just that I'd forgotten about them.

Partly that some of them are things i'm not wildly keen on. Mirroring without source strikes me as a dubious propostion and if someone really wants to they can use other tools, the ipv4 only patch seems disproportionate in size, It seems much easier with urllib3, maybe you could add an IPv4 only option building on top of your urllib3 pull request

But the lack of a good test environment is also an issue. Doing test runs with the full raspbian repo takes freakin ages, but constructing a smaller but still representive repo is something i've never got round to doing.

**Comment by Alextopher** [comment]
I think these concerns were addressed
